# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Experience
    url: '#experience'
    weight: 15
  - name: Projects
    url: '/allprojects'
    weight: 20
  - name: Blog
    url: '#posts'
    weight: 50
  - name: Publications
    url: '#publications'
    weight: 55
  - name: Achievements
    url: '#achievements'
    weight: 30
  - name: Community
    url: '#community'
    weight: 60
  - name: Contact
    url: '#contact'
    weight: 65

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
